export const RSK_TEST_NET_CHAIN_ID = 31;
export const ETH_KOVAN_CHAIN_ID = 42;
export const ETH_MAIN_NET_CHAIN_ID = 1;
export const RSK_MAIN_NET_CHAIN_ID = 30;
export const BSC_MAIN_NET_CHAIN_ID = 56;
export const BSC_TEST_NET_CHAIN_ID = 97;
export const RINKEBY_MAIN_NET_CHAIN_ID = 4;
export const NEW_CHAIN_IDS = [RINKEBY_MAIN_NET_CHAIN_ID, BSC_TEST_NET_CHAIN_ID, BSC_MAIN_NET_CHAIN_ID];
